### ISSUE TITLE
Unhandled error event when using exec

### ISSUE THREAD

**Issue by rasky** [anacierdem/libdragon-docker#46]
Run `libdragon exec mips64-elf-objdump --disassemble build/audioplayer.elf | less`. When you press `Q` to exit less, you get this:

```
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (internal/streams/readable.js:745:14)
    at Socket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}```

**Comment by anacierdem** [comment]
Fixed in https://github.com/anacierdem/libdragon-docker/releases/tag/v10.7.0
